language: ruby
rvm:
  - 2.3.0
sudo: false
script: RUBYOPT=W0 bundle exec rake test
before_script:
  - gem install bundler
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord42.gemfile
  - test/gemfiles/activerecord41.gemfile
  - test/gemfiles/activerecord40.gemfile
  - test/gemfiles/activerecord32.gemfile
matrix:
  allow_failures:
    - gemfile: test/gemfiles/activerecord32.gemfile
