language: ruby
rvm:
  - 2.5.1
sudo: false
script: bundle exec rake test
before_script:
  - gem install bundler
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/actionmailer51.gemfile
  - test/gemfiles/actionmailer50.gemfile
  - test/gemfiles/actionmailer42.gemfile
matrix:
  include:
    gemfile: test/gemfiles/mongoid6.gemfile
    services:
      - mongodb
